name: 'Dusk'
description: 'Dusk, the release creation action'
author: 'Rojan Gh.'
inputs:
  token:
    required: true
    description: Token
  artifact_name:
    required: false
    description: Dawn action artifact name
    default: dawn-outputs
runs:
  using: 'node16'
  main: 'dist/index.js'
